export default{
    REACT_APP_GOOGLE_CLIENT: process.env.REACT_APP_GOOGLE_CLIENT ,
    REACT_APP_FACEBOOK_CLIENT: process.env.REACT_APP_FACEBOOK_CLIENT,
    REACT_APP_PP_CLIENT: process.env.REACT_APP_PP_CLIENT, 
}