export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING ='CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT ='CART_SAVE_PAYMENT';
export const CART_DECREASE ='CART_DECREASE';
export const CART_INCREASE ='CART_INCREASE';

export const CART_ADD_POST_REQUEST= 'CART_ADD_POST_REQUEST';
export const CART_ADD_POST_SUCCESS='CART_ADD_POST_SUCCESS';
export const CART_ADD_POST_FAIL='CART_ADD_POST_FAIL';

export const CART_LIST_REQUEST='CART_LIST_REQUEST';
export const CART_LIST_SUCCESS='CART_LIST_SUCCESS';
export const CART_LIST_FAIL='CART_LIST_FAIL';


export const CART_REMOVE_POST_REQUEST= 'CART_REMOVE_POST_REQUEST';
export const CART_REMOVE_POST_SUCCESS='CART_REMOVE_POST_SUCCESS';
export const CART_REMOVE_POST_FAIL='CART_REMOVE_POST_FAIL';

export const CART_INCREASE_REQUEST= 'CART_INCREASE_REQUEST';
export const CART_INCREASE_SUCCESS= 'CART_INCREASE_SUCCESS';
export const CART_INCREASE_FAIL= 'CART_INCREASE_FAIL';

export const CART_DECREASE_REQUEST= 'CART_DECREASE_REQUEST';
export const CART_DECREASE_SUCCESS= 'CART_DECREASE_SUCCESS';
export const CART_DECREASE_FAIL= 'CART_DECREASE_FAIL';
