export const ADD_ORDER_REQUEST='ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS='ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL='ADD_ORDER_FAIL';
export const CART_EMPTY='CART_EMPTY';

export const HISTORY_REQUEST='HISTORY_REQUEST';
export const HISTORY_SUCCESS='HISTORY_SUCCESS';
export const HISTORY_FAIL='HISTORY_FAIL';

export const VIEW_HISTORY_REQUEST='VIEW_HISTORY_REQUEST';
export const VIEW_HISTORY_SUCCESS='VIEW_HISTORY_SUCCESS';
export const VIEW_HISTORY_FAIL='VIEW_HISTORY_FAIL';

export const REMOVE_ORDER_REQUEST='REMOVE_ORDER_REQUEST';
export const REMOVE_ORDER_SUCCESS='REMOVE_ORDER_SUCCESS';
export const REMOVE_ORDER_FAIL='REMOVE_ORDER_FAIL';