export const ADD_ORDER_REQUEST='ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS='ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL='ADD_ORDER_FAIL';
export const CART_EMPTY='CART_EMPTY';

export const HISTORY_REQUEST='HISTORY_REQUEST';
export const HISTORY_SUCCESS='HISTORY_SUCCESS';
export const HISTORY_FAIL='HISTORY_FAIL';