export const USER_SIGNIN_REQUEST ='USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS ='USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL ='USER_SIGNIN_FAIL';
export const USER_SIGNOUT ='USER_SIGNOUT';

export const USER_REGISTER_REQUEST ='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS ='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL ='USER_REGISTER_FAIL';

export const USER_DETAIL_REQUEST ='USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS ='USER_DETAIL_SUCCESS';
export const USER_DETAIL_FAIL ='USER_DETAIL_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET';

export const FORGOT_EMAIL_FAIL= 'FORGOT_EMAIL_FAIL';
export const FORGOT_EMAIL_SUCCESS= 'FORGOT_EMAIL_SUCCESS';
export const SET_EMAIL_FORGOTPASSWORD= 'SET_EMAIL_FORGOTPASSWORD';
export const RESET_FORGOT_PASSWORD= 'RESET_FORGOT_PASSWORD';
export const VERIFY_OTP_SUCCESS= 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL= 'VERIFY_OTP_FAIL';
export const FORGOT_PASSWORD_SUCCESS= 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL= 'FORGOT_PASSWORD_FAIL';
export const RESET_IS_LOGIN= 'RESET_IS_LOGIN';


export const USER_SIGNIN_FB_REQUEST= 'USER_SIGNIN_FB_REQUEST';
export const USER_SIGNIN_FB_SUCCESS= 'USER_SIGNIN_FB_SUCCESS';
export const USER_SIGNIN_FB_FAIL= 'USER_SIGNIN_FB_FAIL';